#!/usr/bin/env -S deno run --allow-net --allow-read --allow-write

// Convert DFFML logomark SVG to a macOS tray icon PNG.
// All visible (non-alpha) pixels become white (#FFFFFF) while the alpha
// channel is preserved, making it suitable as a macOS "template" image.
//
// Uses @resvg/resvg-wasm (pure WASM, no native addons) and pngjs.
//
// Usage:
//   deno run --allow-net --allow-read --allow-write scripts/logo-svg-to-png.ts

import { Resvg, initWasm } from "npm:@resvg/resvg-wasm";
import { PNG } from "npm:pngjs";

const SVG_URL =
  "https://github.com/dffml/dffml/raw/refs/heads/main/docs/images/logomark.svg";
const OUTPUT_PATH = new URL("../tray-icon.png", import.meta.url).pathname;
const ICON_SIZE = 64; // 64x64 for Retina display support

async function main() {
  // Load the resvg WASM module from the npm cache
  const wasmUrl = new URL(
    "./index_bg.wasm",
    import.meta.resolve("npm:@resvg/resvg-wasm"),
  );
  const wasmBytes = await Deno.readFile(wasmUrl);
  await initWasm(wasmBytes);

  // 1. Fetch the SVG source
  const resp = await fetch(SVG_URL);
  if (!resp.ok) {
    throw new Error(`Failed to fetch SVG: ${resp.status} ${resp.statusText}`);
  }
  const svg = await resp.text();

  // 2. Render SVG to raw RGBA pixels at the target icon size.
  //    `fitTo` with "width" mode preserves aspect ratio within the canvas.
  const resvg = new Resvg(svg, {
    fitTo: { mode: "width", value: ICON_SIZE },
  });
  const rendered = resvg.render();
  const { width, height } = rendered;

  // 3. Make a mutable copy of the raw RGBA pixel buffer.
  //    `pixels` is a Node.js Buffer (subclass of Uint8Array).
  const pixels = new Uint8Array(rendered.pixels);

  // 4. Walk every RGBA pixel (4 bytes per pixel).
  //    Where alpha > 0, set RGB to 255 (white).
  //    Fully transparent pixels (alpha === 0) are left as-is.
  //    Partial-alpha pixels (anti-aliased edges) keep their alpha so edges
  //    look smooth against any background the OS applies.
  for (let i = 0; i < pixels.length; i += 4) {
    if (pixels[i + 3] > 0) {
      pixels[i] = 255;     // R
      pixels[i + 1] = 255; // G
      pixels[i + 2] = 255; // B
      // Alpha channel preserved (index i+3 unchanged)
    }
  }

  // 5. Encode the modified RGBA buffer as PNG using pngjs.
  const png = new PNG({ width, height });
  png.data.set(pixels);

  const pngBuffer = PNG.sync.write(png);

  // 6. Write PNG to disk.
  await Deno.writeFile(OUTPUT_PATH, pngBuffer);

  console.log(
    `Generated ${OUTPUT_PATH} (${width}x${height}, ${
      (pngBuffer.length / 1024).toFixed(1)
    } KB)`,
  );

  // 7. Generate icon.ts with base64-embedded PNG.
  const base64 = btoa(String.fromCharCode(...new Uint8Array(pngBuffer)));
  const iconTsPath = new URL("../icon.ts", import.meta.url).pathname;
  const iconTs = [
    "// Generated by scripts/logo-svg-to-png.ts — do not edit by hand.",
    "// Base64-encoded 64×64 PNG tray icon (white-on-transparent DFFML logomark).",
    "export const TRAY_ICON_BASE64 =",
    `  ${JSON.stringify(base64)};`,
    "",
  ].join("\n");
  await Deno.writeTextFile(iconTsPath, iconTs);
  console.log(`Generated ${iconTsPath} (${iconTs.length} bytes)`);
}

await main();
